export const FACTIONS = [
	{
		id: 1,
		hoyoId: '16',
		faction: 'Cunning Hares',
		icon: 'https://api.hakush.in/zzz/UI/IconCampGentleHouse.webp',
		img: 'https://static.wikia.nocookie.net/zenless-zone-zero/images/c/ce/Faction_Gentle_House_Hero.png',
	},
	{
		id: 2,
		hoyoId: '17',
		faction: 'Victoria Housekeeping Co.',
		icon: 'https://api.hakush.in/zzz/UI/IconCampVictoriaHousekeepingCo..webp',
		img: 'https://static.wikia.nocookie.net/zenless-zone-zero/images/2/2b/Faction_Victoria_Housekeeping_Hero_2.png',
	},
	{
		id: 3,
		hoyoId: '18',
		faction: 'Belobog Heavy Industries',
		icon: 'https://api.hakush.in/zzz/UI/IconCampBelobogIndustries.webp',
		img: 'https://static.wikia.nocookie.net/zenless-zone-zero/images/8/82/Faction_Belobog_Heavy_Industries_Hero_2.png',
	},
	{
		id: 4,
		hoyoId: '77',
		faction: 'Sons of Calydon',
		icon: 'https://api.hakush.in/zzz/UI/IconCampSonsOfCalydon.webp',
		img: 'https://static.wikia.nocookie.net/zenless-zone-zero/images/a/a4/Faction_Sons_of_Calydon_Hero.png',
	},
	{
		id: 5,
		hoyoId: '19',
		faction: 'Obol Squad',
		icon: 'https://api.hakush.in/zzz/UI/IconCampObols.webp',
		img: '',
	},
	{
		id: 6,
		hoyoId: '20',
		faction: 'Hollow Special Operations Section 6',
		icon: 'https://api.hakush.in/zzz/UI/IconCampH.S.O-S6.webp',
		img: 'https://i.redd.it/y8p3g0nrwny91.png',
	},
	{
		id: 7,
		hoyoId: '21',
		faction: 'Criminal Investigation Special Response Team',
		icon: 'https://api.hakush.in/zzz/UI/IconCampN.E.P.S..webp',
		img: 'https://static.wikia.nocookie.net/zenless-zone-zero/images/7/7f/Faction_Criminal_Investigation_Special_Response_Team_Hero_2.png',
	},
	{
		id: 8,
		hoyoId: '86',
		faction: 'Stars of Lyra',
		icon: 'https://api.hakush.in/zzz/UI/IconCampStarsOfLyra.webp',
		img: '',
	},
	{
		id: 9,
		hoyoId: '113',
		faction: 'Mockingbird',
		icon: 'https://api.hakush.in/zzz/UI/IconCampMockingBird.webp',
		img: '',
	},
	{
		id: 10,
		hoyoId: '122',
		faction: 'Yunkui Summit',
		icon: 'https://api.hakush.in/zzz/UI/IconCampSuibian.webp',
		img: '',
	},
	{
		id: 11,
		hoyoId: '126',
		faction: 'Spook Shack',
		icon: 'https://api.hakush.in/zzz/UI/IconCampSpookShack.webp',
		img: '',
	},
] as const;
